const generateBtn = document.getElementById("generate");
const promptInput = document.getElementById("prompt");

const messages = document.getElementById("messages");
const code = document.getElementById("code");
const preview = document.getElementById("preview");
const downloadBtn = document.getElementById("download");


const API_URL =
"https://veltrix-ai-api.stephyyamate.workers.dev";



let files = {

    "index.html": `
<!DOCTYPE html>

<html>

<head>
<title>V Veltrix.ai</title>
</head>


<body>

<h1>
Welcome to V Veltrix.ai
</h1>

<p>
Your AI website will appear here.
</p>

</body>

</html>
`,



    "style.css": `

body {

font-family: Arial;

background:#111;

color:white;

text-align:center;

}

`,



    "app.js": `

console.log("Generated by V Veltrix.ai");

`

};



let currentFile =
"index.html";





function addMessage(text,type){


const div =
document.createElement("div");


div.className =
"message " + type;


div.innerHTML =
text;


messages.appendChild(div);


messages.scrollTop =
messages.scrollHeight;


}







function updateEditor(){


code.textContent =
files[currentFile];


}







function updatePreview(){


preview.srcdoc =

files["index.html"]

+

`

<style>

${files["style.css"]}

</style>

`

+

`

<script>

${files["app.js"]}

<\/script>

`;

}



async function generate(){


const prompt =
promptInput.value.trim();



if(!prompt)
return;



addMessage(
"👤 " + prompt,
"user"
);



addMessage(
"⚡ V Veltrix.ai is creating...",
"ai"
);



try {



const response =
await fetch(

API_URL,

{

method:"POST",

headers:{

"Content-Type":
"application/json"

},


body:JSON.stringify({

prompt:prompt

})

}

);



const data =
await response.json();



console.log(
"Worker Response:",
data
);




if(data.error){

throw new Error(
data.error
);

}




const text =

data.output?.[0]
?.content?.[0]
?.text;



if(!text){

throw new Error(
"No AI output received"
);

}




const project =
JSON.parse(text);





files =
project.files;



addMessage(
"✅ Website generated!",
"ai"
);



currentFile =
"index.html";



document
.querySelectorAll(".file")
.forEach(btn=>{


btn.classList.remove(
"active"
);


if(
btn.dataset.file === currentFile
){

btn.classList.add(
"active"
);

}


});



updateEditor();

updatePreview();



}

catch(error){


console.error(
error
);



addMessage(

"❌ " +
error.message,

"ai"

);


}



}






generateBtn.onclick =
generate;







// ENTER TO SEND

promptInput.addEventListener(
"keydown",
(e)=>{

if(e.key==="Enter"){

generate();

}

});









// FILE BUTTONS


document
.querySelectorAll(".file")
.forEach(button=>{


button.onclick = ()=>{


document
.querySelectorAll(".file")
.forEach(b=>{

b.classList.remove(
"active"
);

});



button.classList.add(
"active"
);



currentFile =
button.dataset.file;



updateEditor();



};


});









// ZIP DOWNLOAD


downloadBtn.onclick =
async()=>{


const zip =
new JSZip();



zip.file(
"index.html",
files["index.html"]
);



zip.file(
"style.css",
files["style.css"]
);



zip.file(
"app.js",
files["app.js"]
);



const blob =
await zip.generateAsync(
{
type:"blob"
}
);



const link =
document.createElement("a");


link.href =
URL.createObjectURL(blob);



link.download =
"Veltrix-Website.zip";


link.click();



};








updateEditor();

updatePreview();
