const generateBtn = document.getElementById("generate");
const promptInput = document.getElementById("prompt");

const messages = document.getElementById("messages");
const codeBox = document.getElementById("code");
const preview = document.getElementById("preview");


let files = {

    "index.html": `
<!DOCTYPE html>
<html>

<head>
<title>Generated Website</title>
</head>

<body>

<h1>Hello from Veltrix.ai</h1>

<p>Your AI generated website.</p>

</body>

</html>
`,

    "style.css": `
body {
    font-family: Arial;
    background:#111;
    color:white;
    text-align:center;
}
`,

    "app.js": `
console.log("Generated by Veltrix.ai");
`

};



function addMessage(text,type){

    const div =
    document.createElement("div");


    div.className =
    type === "user"
    ? "user-message"
    : "ai-message";


    div.textContent = text;


    messages.appendChild(div);


    messages.scrollTop =
    messages.scrollHeight;

}





function updatePreview(){


let html =
files["index.html"];


let css =
"<style>" +
files["style.css"] +
"</style>";


preview.srcdoc =
html + css;


}




function showCode(file){


codeBox.textContent =
files[file];


}




generateBtn.onclick = async()=>{


let prompt =
promptInput.value.trim();



if(!prompt)
return;



addMessage(
"👤 " + prompt,
"user"
);



addMessage(
"🤖 Creating your website...",
"ai"
);



/*
Later replace this with:

fetch("YOUR_AI_API")

*/



setTimeout(()=>{


files["index.html"] = `

<!DOCTYPE html>

<html>

<head>

<title>${prompt}</title>

</head>


<body>

<h1>${prompt}</h1>

<p>
Generated by Veltrix.ai
</p>


<button>
Explore
</button>


</body>

</html>

`;



files["style.css"] = `

body {

background:
linear-gradient(
135deg,
#111,
#402080
);

color:white;

font-family:
Arial;

text-align:center;

padding:100px;

}


button {

background:#8b5cff;

color:white;

border:0;

padding:15px 30px;

border-radius:10px;

}

`;



addMessage(
"✅ Website created!",
"ai"
);



showCode(
"index.html"
);


updatePreview();



},1500);



};



// Load first preview

updatePreview();
