const generateBtn = document.getElementById("generate");
const promptInput = document.getElementById("prompt");

const messages = document.getElementById("messages");
const codeBox = document.getElementById("code");
const preview = document.getElementById("preview");


const WORKER_URL = 
"https://veltrix-ai-api.stephyyamate.workers.dev";


let files = {

    "index.html": `
<!DOCTYPE html>
<html>

<head>
<title>Generated Website</title>
</head>

<body>

<h1>Hello from Veltrix.ai</h1>

<p>Your AI generated website.</p>

</body>

</html>
`,

    "style.css": `
body {
    font-family: Arial;
    background:#111;
    color:white;
    text-align:center;
}
`,

    "app.js": `
console.log("Generated by Veltrix.ai");
`

};



function addMessage(text,type){

    const div = document.createElement("div");

    div.className =
    type === "user"
    ? "user-message"
    : "ai-message";

    div.textContent = text;

    messages.appendChild(div);

    messages.scrollTop =
    messages.scrollHeight;

}



function updatePreview(){

    let html = files["index.html"];

    let css =
    "<style>" +
    files["style.css"] +
    "</style>";

    let js =
    "<script>" +
    files["app.js"] +
    "<\/script>";

    preview.srcdoc =
    html + css + js;

}



function showCode(file){

    codeBox.textContent =
    files[file];

}




generateBtn.onclick = async()=>{


    let prompt =
    promptInput.value.trim();



    if(!prompt)
    return;



    addMessage(
        "👤 " + prompt,
        "user"
    );


    addMessage(
        "🤖 Veltrix is building...",
        "ai"
    );



    try {


        const response = await fetch(
            WORKER_URL,
            {
                method:"POST",

                headers:{
                    "Content-Type":"application/json"
                },

                body:JSON.stringify({
                    prompt: prompt
                })
            }
        );



        const data =
        await response.json();



        console.log(data);



        let output =
        data.output?.[0]?.content?.[0]?.text 
        || "";



        // Try to extract generated files

        const htmlMatch =
        output.match(
        /index\.html[\s\S]*?(?=style\.css|$)/i
        );


        const cssMatch =
        output.match(
        /style\.css[\s\S]*?(?=app\.js|$)/i
        );


        const jsMatch =
        output.match(
        /app\.js[\s\S]*/i
        );



        if(htmlMatch)
        files["index.html"] =
        htmlMatch[0];


        if(cssMatch)
        files["style.css"] =
        cssMatch[0];


        if(jsMatch)
        files["app.js"] =
        jsMatch[0];



        addMessage(
            "✅ Website created!",
            "ai"
        );



        showCode(
            "index.html"
        );


        updatePreview();



    } catch(error){


        console.error(error);


        addMessage(
            "❌ Error connecting to Veltrix AI",
            "ai"
        );


    }


};



// Load preview

updatePreview();
